Create PayablewithBankingEvent.sol
metafy-social/web3-smart-contracts pull request #70
Opened 2022-10-09 08:35 UTC by Gokul-Ks

## Description

Created Solidity contract for simple banking processes <br />

Fixes #63 

## Developer's checklist

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-check on my work

**If changes are made in the code:**

- [x] I have followed the [coding guidelines](https://google.github.io/styleguide/jsguide.html)
- [x] My changes in code generate no new warnings
- [ ] My changes are breaking another fix/feature of the project
- [ ] I have added test cases to show that my feature works
- [ ] I have added relevant screenshots in my PR

2022-10-09 09:39 UTC, advaita-saha requested changes
Complete the mentioned changes

2022-10-09 09:39 UTC, advaita-saha commented on contracts/Misc/PayablewithBankingEvent.sol
> +pragma solidity ^0.4.4;
```suggestion
pragma solidity ^0.8.3;
```

2022-10-10 14:12 UTC, Gokul-Ks reviewed
I have completed the requested change @advaita-saha

2022-10-10 14:15 UTC, advaita-saha commented
Your contract is not getting compiled
https://github.com/metafy-social/web3-smart-contracts/actions/runs/3213673901/jobs/5253511613

Please fix these issues

2024-01-11 01:52 UTC, closed without merging